### ISSUE TITLE
Bug: zsh doesn't have wget by default

### ISSUE THREAD

**Issue by amirhosseinNouri** [MahdiAghaei1/pam#1]
Zsh doesn't have the `wget` by default and executing install.sh will create an empty script instead of installing the actual script inside the `/usr/local/bin/`.

## Step to reproduce
- Uninstall `wget`.
- Edit `install.sh` and remove the line that removes `temp.sh`.
- execute `install.sh`.
- Check `temp.sh` content and it is empty. The empty script have copied to `/usr/local/bin` too.

**Comment by epicmet** [comment]
Thanks to yourself, it is now fixed in 50bd34395711d576467cb3f08f6393808a91c611 ;)
